language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jeffersonpino/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jeffersonpino/react-test  npm run test

after_success:
    - docker build -t jeffersonpino/complex-client ./client
    - docker build -t jeffersonpino/complex-nginx ./nginx
    - docker build -t jeffersonpino/complex-server ./server
    - docker build -t jeffersonpino/complex-worker ./worker
    # log in to the docker CLI

    - echo "$docker_hub_pass" | docker login -u "$docker_hub_user" --password-stdin
    # Push them to docker hub
    - docker push jeffersonpino/complex-client
    - docker push jeffersonpino/complex-nginx
    - docker push jeffersonpino/complex-server
    - docker push jeffersonpino/complex-worker

deploy:
    edge: true    
    provider: elasticbeanstalk
    region  : "us-west-2"
    app     : "multi-docker" 
    env     : "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-496625247561"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY