version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx: 
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'            
    api:
        depends_on:
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:  
            - /app/node_modules #DO NOT map this folder
            - ./server:/app #map everything inside the folder to the app folder on the docker server
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules #DO NOT map this folder
            - ./client:/app #map everything inside the folder to the app folder on the docker server
    worker:
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            dockerfile:  Dockerfile.dev
            context: ./worker
        volumes: 
                - /app/node_modules #DO NOT map this folder
                - ./worker:/app #map everything inside the folder to the app folder on the docker server